/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kl0418;
import java.util.*;

public class App {
    private static Helper helper = new Helper();
    /**
     * Starts the tool rental checkout process
     */
    public static void startCheckout() {
        printInventoryAndPrices();
        helper.getUserInputs();
    }

    /**
     * Loads the store inventories and charging prices
     */
    private static void printInventoryAndPrices() {
        System.out.println("\n CHECKOUT TOOLS \n");
        helper.printInventoryAndPrices();
    }

    public static void main(String[] args) {
        startCheckout();
    }
}
