/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kl0418;

import java.util.*;

public class App {
    private static Helper helper = new Helper();

    /**
     * Starts the tool rental checkout process
     */
    public static void startCheckout() {
        printInventoryAndPrices();
        UserInput userInput = helper.getUserInputs();

        AgreementGenerator generator = new AgreementGenerator(userInput);
        generator.generateAgreement();

        // System.out.println("Tool code: " + userInput.toolCode);
        // System.out.println("Rental day count: " + userInput.rentalDayCount);
        // System.out.println("Discount percent: " + userInput.discountPercent);
        // System.out.println("Checkout date: " + userInput.checkoutDate);
    }

    /**
     * Loads the store inventories and charging prices
     */
    private static void printInventoryAndPrices() {
        System.out.println("\n CHECKOUT TOOLS \n");
        helper.printInventoryAndPrices();
    }

    public static void main(String[] args) {
        boolean isDebug = Arrays.asList(args).contains("debug");
        String debugFlag = isDebug ? "True" : "False";
        ProcessBuilder processBuilder = new ProcessBuilder("RentalDemo");
        processBuilder.environment().put("DEBUG_FLAG", debugFlag);

        startCheckout();
    }
}
